
#ifndef CPP_PROJECT__UTILS_H_
#define CPP_PROJECT__UTILS_H_

enum Personalities {ATTACKER, DEFENDER, SHOGUN, CHANCELLOR, CHAMPION};
enum Holdings {PLAIN, MINE, GOLD_MINE, CRYSTAL_MINE, FARMS, SOLO, STRONGHOLD};
enum Followers {FOOTSOLDIER, ARCHER, SIEGER, CAVALRY, NAVAL, BUSHIDO};
enum Items {KATANA, SPEAR, BOW, NINJATO, WAKIZASHI};

#endif //CPP_PROJECT__UTILS_H_
